{
 "title": "Overview (Version: 1.0)",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30m",
 "panels": [
  {
   "title": "Time Period",
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_FORMAT(MIN(interval_start), '%d-%m-%Y') AS \"Start Date\",\n  DATE_FORMAT(MAX(interval_start), '%d-%m-%Y') AS \"End Date\"\nFROM energy_consumption;\n"
    }
   ]
  },
  {
   "title": "Total Consumption",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(consumption) AS total_consumption_Kw\nFROM energy_consumption\n"
    }
   ]
  },
  {
   "title": "Yesterday's Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(consumption) AS total_consumption\nFROM energy_consumption\nWHERE DATE(interval_start) = CURDATE() - INTERVAL 1 DAY;\n"
    }
   ]
  },
  {
   "title": "Average Consumption",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  AVG(consumption) AS average_consumption_Kw\nFROM energy_consumption\n"
    }
   ]
  },
  {
   "title": "Min Consumption",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  MIN(consumption) AS min_consumption_Kw\nFROM energy_consumption\n"
    }
   ]
  },
  {
   "title": "Max Consumption",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  MAX(consumption) AS max_consumption_Kw\nFROM energy_consumption\n"
    }
   ]
  },
  { "title": "Consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Electric Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "dataset": "octopus",
     "rawSql": "SELECT consumption, interval_start, interval_end\nFROM energy_consumption;\n"
    }
   ]
  },
  {
   "title": "Seven Days Usage",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "rawSql": "SELECT DATE(interval_start) AS date, DAYNAME(interval_start) AS day_of_week, SUM(consumption) AS Consumption\nFROM energy_consumption\nWHERE interval_start >= DATE_SUB(CURDATE(), INTERVAL 7 DAY)\nGROUP BY DATE(interval_start), DAYNAME(interval_start)\nORDER BY DATE(interval_start) ASC;\n"
    }
   ]
  },
  { "title": "Cost", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Time Period",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_FORMAT(MIN(valid_from), '%d-%m-%Y') AS \"Start Date\",\n  DATE_FORMAT(MAX(valid_from), '%d-%m-%Y') AS \"End Date\"\nFROM unit_rates;\n"
    }
   ]
  },
  {
   "title": "Price for the next 30 Min",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Pence" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value_inc_vat\nFROM unit_rates\nWHERE CONVERT_TZ(valid_from, '+00:00', '+01:00') <= CONVERT_TZ(NOW(), '+00:00', '+01:00')\n  AND CONVERT_TZ(valid_to, '+00:00', '+01:00') >= CONVERT_TZ(NOW(), '+00:00', '+01:00')\nORDER BY valid_from DESC\nLIMIT 1;\n"
    }
   ]
  },
  {
   "title": "Average Price Per Kw",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Pence" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  AVG(value_inc_vat) AS value_inc_vat\nFROM unit_rates\n"
    }
   ]
  },
  {
   "title": "Max Price Per Kw",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Pence" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  MAX(value_inc_vat) AS value_inc_vat\nFROM unit_rates\n"
    }
   ]
  },
  {
   "title": "Min Price Per Kw",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Pence" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  MIN(value_inc_vat) AS value_inc_vat\nFROM unit_rates\n"
    }
   ]
  },
  {
   "title": "Est Usage for Next Day ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(consumption) AS estimated_consumption\nFROM energy_consumption\nWHERE interval_start >= CURDATE() - INTERVAL 7 DAY\n  AND interval_start < CURDATE()\n"
    }
   ]
  },
  {
   "title": "Unit Rates",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "dataset": "octopus",
     "rawSql": "SELECT valid_from, value_exc_vat, value_inc_vat\nFROM unit_rates\n"
    }
   ]
  }
 ]
}